import type { Book, SliderItem, Partner, Order } from "./types"

export const mockBooks: Book[] = [
  {
    id: "1",
    title: "Abaya Élégance Dorée",
    author: "Baraa",
    category: "abaya",
    size: "M",
    color: "or",
    price: 189.99,
    promoPrice: 149.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Abaya luxueuse avec broderies dorées délicates. Coupe fluide et élégante, parfaite pour les occasions spéciales.",
    rating: 4.9,
    reviews: 124,
    status: "En stock",
    fabric: "Crêpe premium avec broderies dorées",
    care: "Lavage à la main recommandé, séchage à plat",
  },
  {
    id: "2",
    title: "Hijab Soie Premium Noir",
    author: "Baraa",
    category: "hijab",
    size: "Unique",
    color: "noir",
    price: 45.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Hijab en soie naturelle de haute qualité. Doux, respirant et facile à draper.",
    rating: 4.8,
    reviews: 289,
    status: "En stock",
    fabric: "100% Soie naturelle",
    care: "Lavage délicat à 30°C",
  },
  {
    id: "3",
    title: "Jilbab Moderne Beige",
    author: "Baraa",
    category: "jilbab",
    size: "L",
    color: "beige",
    price: 129.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Jilbab contemporain avec coupe moderne. Confortable et élégant pour le quotidien.",
    rating: 4.7,
    reviews: 156,
    status: "En stock",
    fabric: "Jersey stretch premium",
    care: "Lavage machine 40°C",
  },
  {
    id: "4",
    title: "Kaftan Royal Bronze",
    author: "Baraa",
    category: "kaftan",
    size: "XL",
    color: "bronze",
    price: 249.99,
    promoPrice: 199.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Kaftan majestueux avec détails brodés. Idéal pour les cérémonies et événements.",
    rating: 5.0,
    reviews: 203,
    status: "En stock",
    fabric: "Velours côtelé avec broderies",
    care: "Nettoyage à sec uniquement",
  },
  {
    id: "5",
    title: "Ensemble Prière Rose",
    author: "Baraa",
    category: "ensemble",
    size: "M",
    color: "rose",
    price: 79.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Ensemble complet pour la prière. Léger, confortable et facile à enfiler.",
    rating: 4.6,
    reviews: 178,
    status: "En stock",
    fabric: "Coton jersey doux",
    care: "Lavage machine 30°C",
  },
  {
    id: "6",
    title: "Abaya Quotidienne Noire",
    author: "Baraa",
    category: "abaya",
    size: "S",
    color: "noir",
    price: 99.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Abaya simple et élégante pour tous les jours. Coupe classique intemporelle.",
    rating: 4.8,
    reviews: 412,
    status: "En stock",
    fabric: "Polyester premium anti-froissement",
    care: "Lavage machine 40°C",
  },
  {
    id: "7",
    title: "Hijab Collection Pastel",
    author: "Baraa",
    category: "hijab",
    size: "Unique",
    color: "beige",
    price: 35.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Collection de hijabs aux couleurs pastel douces. Pack de 3 pièces.",
    rating: 4.7,
    reviews: 267,
    status: "En stock",
    fabric: "Mousseline légère",
    care: "Lavage délicat",
  },
  {
    id: "8",
    title: "Abaya Cérémonie Bordeaux",
    author: "Baraa",
    category: "abaya",
    size: "L",
    color: "bordeaux",
    price: 219.99,
    promoPrice: 179.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Abaya sophistiquée couleur bordeaux avec finitions luxueuses. Pour vos événements spéciaux.",
    rating: 4.9,
    reviews: 156,
    status: "En stock",
    fabric: "Crêpe satiné avec perles",
    care: "Nettoyage à sec recommandé",
  },
]

export const mockSliders: SliderItem[] = [
  {
    id: "1",
    title: "Collection Printemps 2026",
    subtitle: "Découvrez nos nouvelles abayas dorées",
    image: "/DEMO-BANNER.png",
    cta: "Découvrir",
    link: "/books",
  },
  {
    id: "2",
    title: "Élégance Intemporelle",
    subtitle: "Mode islamique de luxe",
    image: "/demo-banner2.png",
    cta: "Voir la collection",
    link: "/books",
  }
]

export const mockPartners: Partner[] = [
  {
    id: "1",
    name: "Amira Boutique",
    email: "amira@example.com",
    phone: "+216 92 345 678",
    productTitle: "Collection Hijabs Premium",
    category: "hijab",
    size: "Unique",
    color: "or",
    description: "Collection exclusive de hijabs en soie avec finitions dorées",
    createdAt: new Date("2024-01-15"),
  },
]

export const mockOrders: Order[] = [
  {
    id: "1",
    bookId: "1",
    quantity: 2,
    totalPrice: 37.98,
    customerName: "Amina Jouini",
    customerEmail: "amina@example.com",
    createdAt: new Date("2024-01-10"),
  },
]
