import type { Book, SliderItem, Partner, Order } from "./types"

export const mockBooks: Book[] = [
  {
    id: "1",
    title: "Abaya Élégance Dorée",
    author: "Baraa",
    category: "abaya",
    sizes: ["S", "M", "L", "XL"],
    colors: ["noir", "or", "bronze", "Noir et Or"],
    colorOptions: [
      { value: "noir", label: "Noir", isPredefined: true, colorCodes: ["#000000"] },
      { value: "or", label: "Or", isPredefined: true, colorCodes: ["#FFD700"] },
      { value: "bronze", label: "Bronze", isPredefined: true, colorCodes: ["#CD7F32"] },
      { value: "Noir et Or", label: "Noir et Or", isPredefined: false, colorCodes: ["#000000", "#FFD700"] },
    ],
    price: 189.99,
    promoPrice: 149.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Abaya luxueuse avec broderies dorées délicates. Coupe fluide et élégante, parfaite pour les occasions spéciales.",
    rating: 4.9,
    reviews: 124,
    status: "En stock",
    fabric: "Crêpe premium avec broderies dorées",
    care: "Lavage à la main recommandé, séchage à plat",
  },
  {
    id: "2",
    title: "Hijab Soie Premium",
    author: "Baraa",
    category: "hijab",
    sizes: ["Unique"],
    colors: ["noir", "blanc", "beige", "rose", "bleu", "Blanc et Rose"],
    colorOptions: [
      { value: "noir", label: "Noir", isPredefined: true, colorCodes: ["#000000"] },
      { value: "blanc", label: "Blanc", isPredefined: true, colorCodes: ["#FFFFFF"] },
      { value: "beige", label: "Beige", isPredefined: true, colorCodes: ["#F5F5DC"] },
      { value: "rose", label: "Rose", isPredefined: true, colorCodes: ["#FFC0CB"] },
      { value: "bleu", label: "Bleu", isPredefined: true, colorCodes: ["#3B82F6"] },
      { value: "Blanc et Rose", label: "Blanc et Rose", isPredefined: false, colorCodes: ["#FFFFFF", "#FFC0CB"] },
    ],
    price: 45.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Hijab en soie naturelle de haute qualité. Doux, respirant et facile à draper.",
    rating: 4.8,
    reviews: 289,
    status: "En stock",
    fabric: "100% Soie naturelle",
    care: "Lavage délicat à 30°C",
  },
  {
    id: "3",
    title: "Jilbab Moderne",
    author: "Baraa",
    category: "jilbab",
    sizes: ["M", "L", "XL"],
    colors: ["beige", "noir", "vert", "Beige et Bronze"],
    colorOptions: [
      { value: "beige", label: "Beige", isPredefined: true, colorCodes: ["#F5F5DC"] },
      { value: "noir", label: "Noir", isPredefined: true, colorCodes: ["#000000"] },
      { value: "vert", label: "Vert", isPredefined: true, colorCodes: ["#22C55E"] },
      { value: "Beige et Bronze", label: "Beige et Bronze", isPredefined: false, colorCodes: ["#F5F5DC", "#CD7F32"] },
    ],
    price: 129.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Jilbab contemporain avec coupe moderne. Confortable et élégant pour le quotidien.",
    rating: 4.7,
    reviews: 156,
    status: "En stock",
    fabric: "Jersey stretch premium",
    care: "Lavage machine 40°C",
  },
  {
    id: "4",
    title: "Kaftan Royal",
    author: "Baraa",
    category: "kaftan",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["bronze", "or", "bordeaux", "Bordeaux et Or"],
    colorOptions: [
      { value: "bronze", label: "Bronze", isPredefined: true, colorCodes: ["#CD7F32"] },
      { value: "or", label: "Or", isPredefined: true, colorCodes: ["#FFD700"] },
      { value: "bordeaux", label: "Bordeaux", isPredefined: true, colorCodes: ["#800020"] },
      { value: "Bordeaux et Or", label: "Bordeaux et Or", isPredefined: false, colorCodes: ["#800020", "#FFD700"] },
    ],
    price: 249.99,
    promoPrice: 199.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Kaftan majestueux avec détails brodés. Idéal pour les cérémonies et événements.",
    rating: 5.0,
    reviews: 203,
    status: "En stock",
    fabric: "Velours côtelé avec broderies",
    care: "Nettoyage à sec uniquement",
  },
  {
    id: "5",
    title: "Ensemble Prière",
    author: "Baraa",
    category: "ensemble",
    sizes: ["S", "M", "L"],
    colors: ["rose", "blanc", "beige"],
    colorOptions: [
      { value: "rose", label: "Rose", isPredefined: true, colorCodes: ["#FFC0CB"] },
      { value: "blanc", label: "Blanc", isPredefined: true, colorCodes: ["#FFFFFF"] },
      { value: "beige", label: "Beige", isPredefined: true, colorCodes: ["#F5F5DC"] },
    ],
    price: 79.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Ensemble complet pour la prière. Léger, confortable et facile à enfiler.",
    rating: 4.6,
    reviews: 178,
    status: "En stock",
    fabric: "Coton jersey doux",
    care: "Lavage machine 30°C",
  },
  {
    id: "6",
    title: "Abaya Quotidienne",
    author: "Baraa",
    category: "abaya",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["noir", "bleu", "vert", "Bleu et Blanc"],
    colorOptions: [
      { value: "noir", label: "Noir", isPredefined: true, colorCodes: ["#000000"] },
      { value: "bleu", label: "Bleu", isPredefined: true, colorCodes: ["#3B82F6"] },
      { value: "vert", label: "Vert", isPredefined: true, colorCodes: ["#22C55E"] },
      { value: "Bleu et Blanc", label: "Bleu et Blanc", isPredefined: false, colorCodes: ["#3B82F6", "#FFFFFF"] },
    ],
    price: 99.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Abaya simple et élégante pour tous les jours. Coupe classique intemporelle.",
    rating: 4.8,
    reviews: 412,
    status: "En stock",
    fabric: "Polyester premium anti-froissement",
    care: "Lavage machine 40°C",
  },
  {
    id: "7",
    title: "Hijab Collection Pastel",
    author: "Baraa",
    category: "hijab",
    sizes: ["Unique"],
    colors: ["beige", "rose", "blanc"],
    colorOptions: [
      { value: "beige", label: "Beige", isPredefined: true, colorCodes: ["#F5F5DC"] },
      { value: "rose", label: "Rose", isPredefined: true, colorCodes: ["#FFC0CB"] },
      { value: "blanc", label: "Blanc", isPredefined: true, colorCodes: ["#FFFFFF"] },
    ],
    price: 35.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Collection de hijabs aux couleurs pastel douces. Pack de 3 pièces.",
    rating: 4.7,
    reviews: 267,
    status: "En stock",
    fabric: "Mousseline légère",
    care: "Lavage délicat",
  },
  {
    id: "8",
    title: "Abaya Cérémonie Bordeaux",
    author: "Baraa",
    category: "abaya",
    sizes: ["M", "L", "XL"],
    colors: ["bordeaux", "noir"],
    colorOptions: [
      { value: "bordeaux", label: "Bordeaux", isPredefined: true, colorCodes: ["#800020"] },
      { value: "noir", label: "Noir", isPredefined: true, colorCodes: ["#000000"] },
    ],
    price: 219.99,
    promoPrice: 179.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Abaya sophistiquée couleur bordeaux avec finitions luxueuses. Pour vos événements spéciaux.",
    rating: 4.9,
    reviews: 156,
    status: "En stock",
    fabric: "Crêpe satiné avec perles",
    care: "Nettoyage à sec recommandé",
  },
  {
    id: "premium-collection",
    title: "Abaya Prestige Collection - Édition Limitée",
    author: "Baraa",
    category: "abaya",
    sizes: ["S", "M", "L", "XL", "XXL"],
    // ✨ EXEMPLE COMPLET: Mélange de tous les types de couleurs
    colors: [
      // Couleurs prédéfinies (3)
      "noir",
      "blanc", 
      "or",
      // Couleurs personnalisées simples (2)
      "Bleu Nuit",
      "Vert Émeraude",
      // Combinaisons de couleurs (3)
      "Noir et Or",
      "Blanc et Rose",
      "Bordeaux et Or"
    ],
    colorOptions: [
      // Prédéfinies
      { value: "noir", label: "Noir", isPredefined: true, colorCodes: ["#000000"] },
      { value: "blanc", label: "Blanc", isPredefined: true, colorCodes: ["#FFFFFF"] },
      { value: "or", label: "Or", isPredefined: true, colorCodes: ["#FFD700"] },
      // Personnalisées simples
      { value: "Bleu Nuit", label: "Bleu Nuit", isPredefined: false, colorCodes: ["#191970"] },
      { value: "Vert Émeraude", label: "Vert Émeraude", isPredefined: false, colorCodes: ["#50C878"] },
      // Combinaisons
      { value: "Noir et Or", label: "Noir et Or", isPredefined: false, colorCodes: ["#000000", "#FFD700"] },
      { value: "Blanc et Rose", label: "Blanc et Rose", isPredefined: false, colorCodes: ["#FFFFFF", "#FFC0CB"] },
      { value: "Bordeaux et Or", label: "Bordeaux et Or", isPredefined: false, colorCodes: ["#800020", "#FFD700"] },
    ],
    price: 299.99,
    promoPrice: 249.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Collection prestige avec 8 options de couleurs exclusives. Mélange harmonieux de couleurs classiques, personnalisées et combinaisons élégantes. Édition limitée avec broderies main et finitions luxueuses.",
    rating: 5.0,
    reviews: 89,
    status: "En stock",
    fabric: "Soie naturelle premium avec broderies dorées à la main",
    care: "Nettoyage à sec uniquement - Produit délicat",
  },
  {
    id: "kaftan-luxury-mix",
    title: "Kaftan Luxury - Mix Standard & Personalized",
    author: "Baraa",
    category: "kaftan",
    sizes: ["M", "L", "XL", "XXL"],
    // ✨ EXAMPLE: Standard colors + Personalized colors + Combinations
    colors: [
      // Standard predefined colors (4)
      "bleu",        // Blue (standard)
      "blanc",       // White (standard)
      "marron",      // Marron/Brown (standard)
      "bordeaux",    // Red/Bordeaux (standard)
      // Personalized colors (2)
      "Bleu Royal",  // Custom blue
      "Rouge Rubis", // Custom red
      // Combinations (2)
      "Blue and White",
      "Red and Gold"
    ],
    colorOptions: [
      // Standard colors
      { value: "bleu", label: "Bleu", isPredefined: true, colorCodes: ["#3B82F6"] },
      { value: "blanc", label: "Blanc", isPredefined: true, colorCodes: ["#FFFFFF"] },
      { value: "marron", label: "Marron", isPredefined: true, colorCodes: ["#8B4513"] },
      { value: "bordeaux", label: "Bordeaux", isPredefined: true, colorCodes: ["#800020"] },
      // Personalized colors
      { value: "Bleu Royal", label: "Bleu Royal", isPredefined: false, colorCodes: ["#4169E1"] },
      { value: "Rouge Rubis", label: "Rouge Rubis", isPredefined: false, colorCodes: ["#E0115F"] },
      // Combinations
      { value: "Blue and White", label: "Blue and White", isPredefined: false, colorCodes: ["#3B82F6", "#FFFFFF"] },
      { value: "Red and Gold", label: "Red and Gold", isPredefined: false, colorCodes: ["#E0115F", "#FFD700"] },
    ],
    price: 279.99,
    promoPrice: 229.99,
    image: "/placeholder.jpg",
    images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
    description: "Kaftan luxueux démontrant le mélange parfait de couleurs standards (Bleu, Blanc, Marron, Bordeaux) avec des couleurs personnalisées (Bleu Royal, Rouge Rubis) et des combinaisons élégantes (Blue and White, Red and Gold). 8 options de couleurs pour un choix maximal.",
    rating: 4.9,
    reviews: 67,
    status: "En stock",
    fabric: "Velours premium avec broderies perlées",
    care: "Nettoyage à sec recommandé",
  },
]

export const mockSliders: SliderItem[] = [
  {
    id: "1",
    title: "Collection Printemps 2026",
    subtitle: "Découvrez nos nouvelles abayas dorées",
    image: "/DEMO-BANNER.png",
    cta: "Découvrir",
    link: "/articles",
  },
  {
    id: "2",
    title: "Élégance Intemporelle",
    subtitle: "Mode islamique de luxe",
    image: "/demo-banner2.png",
    cta: "Voir la collection",
    link: "/articles",
  }
]

export const mockPartners: Partner[] = [
  {
    id: "1",
    name: "Amira Boutique",
    email: "amira@example.com",
    phone: "+216 92 345 678",
    productTitle: "Collection Hijabs Premium",
    category: "hijab",
    sizes: ["Unique"],
    colors: ["or", "bronze"],
    description: "Collection exclusive de hijabs en soie avec finitions dorées",
    createdAt: new Date("2024-01-15"),
  },
]

export const mockOrders: Order[] = []
